# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75eab17b78aeb2ede7061fc8da26c187ef5ac8d093c14cf2425cc271d0b727b2cda275ab7f9770da9a917f62b88af79c4826d331a2a8b660eb7cfaf402473988
  skroutz_client_id: HztLDyp9iACGFN9GL92V-Q==
  skroutz_client_secret: ih83gAyzUacRbnSa6
test:
  secret_key_base: c69cb6db1a4e101679b73670d80e8cd59f2e6c55a99c29c5405fefb1257bfa412e0139ee3d4797a1850067415526ca00527e55f0e82ea44455bf1527ae8b17f3
  skroutz_client_id: HztLDyp9iACGFN9GL92V-Q==
  skroutz_client_secret: ih83gAyzUacRbnSa6
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  skroutz_client_id: HztLDyp9iACGFN9GL92V-Q==
  skroutz_client_secret: ih83gAyzUacRbnSa6